spring:
  new:
    key: c53ab64151ef00e4058b7e2e8894c99e
    url: https://v.juhe.cn/toutiao/index
  web:
   cors:
    origin: '*'
    credentials: false
    methods: '*'
   flow:
    period: 3
    limit: 100
    block: 30
  mail:
    password: BEAGDULMBXDYOGGO
    username: zhennan996@163.com
    host: smtp.163.com
  rabbitmq:
    host: 8.134.93.74
    username: xiao
    password: feiwu
    virtual-host: /
    port: 5672
    listener:
      simple:
        # 重试机制
        retry:
          enabled: true #是否开启消费者重试
          max-attempts: 3 #最大重试次数
          initial-interval: 4000ms #重试间隔时间（单位毫秒）
          max-interval: 12000ms #重试最大时间间隔（单位毫秒）
          multiplier: 2 #间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
  data:
    redis:
      port: 6379
      password: feiwu
      host: 8.134.93.74
  security:
    jwt:
     expire: 72
     key: xznzzhxzn
     limit:
      base: 10
      upgrade: 300
      frequency: 30
    filter:
      order: -100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/monitor?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: feiwu
  minio:
    endpoint: 'http://8.134.93.74:9000'
    username: 'minio'
    password: 'password'
  weather:
    key: 7554413210914257a74e8a1fddc1931f
server:
  port: 8081
